### ISSUE TITLE
warning on export -regression (works on earlier commits of madparts)

### ISSUE THREAD

**Issue by spanner888** [andete/madparts#92]
Somewhere bewtween commit 6370e023bc76eee995c77207fb7ec1309c7b818f and latest code on2015-07-26 I now get this warning when exporting my monster footprint:
export failure: Traceback (most recent call last):
File "/home/spanner888/Documents/DevID/madparts/main/madparts.py", line 387, in _export_footprint exporter.export_footprint(self.executed_footprint)
File "/home/spanner888/Documents/DevID/madparts/export/kicad.py", line 349, in export_footprint }.get(shape['type'], unknown)(shape)
File "/home/spanner888/Documents/DevID/madparts/export/kicad.py", line 116, in pad want_paste = sahpe['paste'] keyError: 'paste'

happy to send the code that triggers this - how should I send it?

**Comment by spanner888** [comment]
Thanks - that does the trick very nicely
